version: "3"

networks:
  fastapi_net:
    driver: bridge

services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    networks:
      - fastapi_net

  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - collector
    networks:
      - fastapi_net

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #   - "16686:16686"
  #   depends_on:
  #     - collector
  #   networks:
  #   - fastapi_net
