receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed
  # otlp/jaeger:
  #   endpoint: "jaeger:4317"
  #   tls:
  #     insecure: true

service:
  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ debug ]
    # traces:
    #   receivers: [ otlp ]
    #   exporters: [ debug, otlp/jaeger ]
